### ISSUE TITLE
"npm run build" failing

### ISSUE THREAD

**Issue by zsilver1** [arimah/condict#6]
Hey!

Hope you're doing well! I figured now that the README has some build directions I might give it a try, but running into an error on the last step. It seems to build `graphql-typer` without any issues, but then fails on a couple of the utils packages:

```
condict info build Matching packages: inflect, ipa, x-sampa
condict info build Running build command in matching packages
ERR! lerna Unknown arguments: @condict/ipa, @condict/x-sampa
condict info build Terminated by error: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @condict/workspace@ build: `node scripts/build -g build-tools && node scripts/build -g utils && node scripts/build -g server && node scripts/build -g ui`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @condict/workspace@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I'll attach the full log file in case that helps:
[2020-09-13T15_06_53_811Z-debug.log](https://github.com/arimah/condict/files/5214379/2020-09-13T15_06_53_811Z-debug.log)

Let me know if there's any other info you need. Thanks!

**Comment by arimah** [comment]
Hey again! :D 

Ah, ever the trusty fan, aren't you! It's rather exciting in a way to get an actual bug report from someone other than myself. I'm sorry you're having trouble getting started, though! It seems my assumption was incorrect: just because it works on Linux doesn't mean it works on macOS.

I _think_ I've managed to figure out the cause of this problem, as described in #7. Since I don't have a macOS machine to test with, do you suppose you could check out that branch and see if it resolves your issue?

Thank you for your report. :)

**Comment by zsilver1** [comment]
No prob :-) got everything built now.

**Comment by arimah** [comment]
Awesome! Thank you for the help. 💚
